### ISSUE TITLE
Consider and make clear if atlas-ftag-tools is an application or a library

### ISSUE THREAD

**Issue by matthewfeickert** [umami-hep/atlas-ftag-tools#11]
:wave: Hi. At the moment you have pinned all of your runtime dependencies

https://github.com/umami-hep/atlas-ftag-tools/blob/ed45b0d369d332ef5ac0d47ff1a126b368569b69/pyproject.toml#L9-L13

this leads me to believe that you view `atlas-ftag-tools` as an [application and not a library](https://iscinumpy.dev/post/app-vs-library/).

If you do view it as an application then I would encourage you to lean into that and remove any floating of patch verions

https://github.com/umami-hep/atlas-ftag-tools/blob/ed45b0d369d332ef5ac0d47ff1a126b368569b69/pyproject.toml#L11

and additionally package a `pip-tools` lock file with the repository.

If you view `atlas-ftag-tools` as a library then please [do not pin your dependencies](https://iscinumpy.dev/post/bound-version-constraints/) like this. This will cause things to break.

**Comment by samvanstroud** [comment]
Hi @matthewfeickert! thanks for the comments, let me know if your concerns are addressed by #12, cheers.
