### ISSUE TITLE
Copy attributes to virtual files

### ISSUE THREAD

**Issue by samvanstroud** [umami-hep/atlas-ftag-tools#19]
We should loop over the source files are find attributes which are common across all files, and copy them to the output file

**Comment by longwills** [comment]
Hi, I got a quick solution that copies the attributes by adding:
            with h5py.File(fnames[0]) as g:
                 for name, value in g[group].attrs.items():
                      f[group].attrs[name] = value
after
    with h5py.File(out_fname, "w") as f:
        for group in h5py.File(fnames[0]):
            layout = get_virtual_layout(fnames, group)
            f.create_virtual_dataset(group, layout)
            
I have put the PR here: https://github.com/umami-hep/atlas-ftag-tools/pull/20
